---
output:
  xaringan::moon_reader:
    css: ["rladies", "rladies-fonts"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.retina = 3, warning = FALSE, message = FALSE)
library(icon)      
library(tidyverse) 
```


class: center, top

#  Setting up the R Environment

.left[
Download [R](https://cran.r-project.org/) according to your OS.
]

<br>

.left[
Download [RStudio](https://www.rstudio.com/) according to your OS.
]

<br>

.left[
Create a new project in RStudio: `File -> New Project -> New Directory -> New Project (Netball Analysis)`
]

<br>

.left[
Ensure the packages below are installed and up-to-date:

```{r LoadPackagesForWorkshop, eval = FALSE}
WCSFWorkshopPackages <- c(
    'readr',
    'tidyverse', 
    'here',
    'usethis')

install.packages(WCSFWorkshopPackages)

```
]



